name: Rewrite ALL Commit History

on:
  workflow_dispatch: 

jobs:
  rewrite-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Rewrite Author Info for ALL branches
      run: |
        # Впиши сюда свои реальные данные GitHub
        CORRECT_NAME="SofijaBeljakova"
        CORRECT_EMAIL="sofija.beljakova@tptplive.ee"
        
        export FILTER_BRANCH_SQUELCH_WARNING=1
        
     
        git filter-branch -f --env-filter "
            export GIT_AUTHOR_NAME='$CORRECT_NAME'
            export GIT_AUTHOR_EMAIL='$CORRECT_EMAIL'
            export GIT_COMMITTER_NAME='$CORRECT_NAME'
            export GIT_COMMITTER_EMAIL='$CORRECT_EMAIL'
        " --tag-name-filter cat -- --all

    - name: Force Push ALL branches at once
      run: |
       
        git push origin --force --all
