name: Daily Auto Commit

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set dynamic branch name
      run: |
        export TZ="Europe/Tallinn"
        START_SEC=$(date -d "2026-05-23" +%s)
        CURRENT_SEC=$(date +%s)
        DIFF_SEC=$(( CURRENT_SEC - START_SEC ))
        DAYS=$(( DIFF_SEC / 86400 ))
        WEEK=$(( (DAYS / 7) + 1 ))
        if [ $WEEK -gt 4 ]; then WEEK=4; fi
        if [ $WEEK -lt 1 ]; then WEEK=1; fi
        echo "BRANCH_NAME=week$WEEK" >> $GITHUB_ENV

    - name: Run script
      run: python auto_commit.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        if [ ! -f README.md ]; then
          touch README.md
        fi
        git checkout $BRANCH_NAME || git checkout -b $BRANCH_NAME
        git add README.md
        git commit -m "Automatic commit for today" || echo "No changes to commit"
        git push origin $BRANCH_NAME
